name: Format
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - development
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download cljfmt installer
        run: curl -L -O https://raw.githubusercontent.com/weavejester/cljfmt/HEAD/install.sh
      - name: Make cljfmt installer executable
        run: chmod +x install.sh
      - name: Install cljfmt
        run: sudo ./install.sh
      - name: Check formatting
        run: cljfmt check ./src/ ./test/
