name: Lint
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - development
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download clj-kondo installer
        run: curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
      - name: Make clj-kondo installer executable
        run: chmod +x install-clj-kondo
      - name: Install clj-kondo
        run: sudo ./install-clj-kondo
      - name: Lint
        run: clj-kondo --lint ./src/ ./test/
